/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import Core.OperationCalculate;
import Operations.Addition;
import Operations.Division;
import Operations.Multiplication;
import Operations.Subtraction;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());

        OperationCalculate add = new Addition();
        OperationCalculate sub = new Subtraction();
        OperationCalculate mult = new Multiplication();
        OperationCalculate div = new Division();

        double a = 50, b = 400;

        System.out.println("TESTE: ");

        System.out.println("Addition: " + add.Calculate(a,b));
        System.out.println("Subtraction: " + sub.Calculate(a,b));
        System.out.println("Multiplication: " + mult.Calculate(a,b));
        System.out.println("Division: " + div.Calculate(a,b));
    }
}
